---

dependencies: []

galaxy_info:

  role_name: 'php/env'
  author: 'Mariano Barcia, Maciej Delmanowski'
  description: 'Define debops.php environment variables'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.2.0'
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - quantal
    - raring
    - saucy
    - trusty
    - xenial
  - name: Debian
    versions:
    - wheezy
    - jessie
  galaxy_tags:
  - development
  - web
  - php
  - php5
  - php7
